# Generated by Django 4.2 on 2026-05-17 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, default='💰', max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('transaction_date', models.DateTimeField()),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank Transfer')], default='CASH', max_length=20)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'transaction_date'], name='expenses_user_id_70315c_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'category'], name='expenses_user_id_ea8763_idx'),
        ),
    ]
